### ISSUE TITLE
[Remove fake links] Add support for tumblr.com

### ISSUE THREAD

**Issue by Keith94** [Infocatcher/UserScripts#12]
**Page:** http://gamebombru.tumblr.com/post/157380151324/unprofessional-fridays-02172017

**Redirect link:** http://t.umblr.com/redirect?z=https%3A%2F%2Fmega.nz%2F%23%21yUoUXBab%21e97ZRB0tgPInC6ItNoa5GjPvqL8SUNB541H9zdLkVcc&t=NjA5ZjhiMDk3Y2VhY2MyMDQxOGM2NGVhMDU2NjhlYjdhMGQxNzZiMCxLMkN0UERuUA%3D%3D&b=t%3A5LULEsU7myDRSIxlx5g_5A&p=http%3A%2F%2Fgamebombru.tumblr.com%2Fpost%2F157380151324%2Funprofessional-fridays-02172017&m=0

**Actual link:** https://mega.nz/#!yUoUXBab!e97ZRB0tgPInC6ItNoa5GjPvqL8SUNB541H9zdLkVcc

**Comment by Infocatcher** [comment]
Test page is gone... but should work: f5ea8e4f6cce1867f19ef4bf6ee905be29789d8e
From https://www.google.ru/search?q=umblr.com/redirect%3F+site:tumblr.com:
https://unwrapping.tumblr.com/post/128241551157/redirect-url-link-posts
http://mlab-moonda.tumblr.com/

**Comment by Keith94** [comment]
Thanks!
