### ISSUE TITLE
[Remove fake links] outgoing.prod.mozaws.net

### ISSUE THREAD

**Issue by Keith94** [Infocatcher/UserScripts#13]
**Page:** https://addons.mozilla.org/en-US/firefox/addon/private-tab/

**Support page (with redirect):** https://outgoing.prod.mozaws.net/v1/f4c650386181c769e2dc55219cea85f1f23002e9fd35c007b6cccf2c9e2b45bc/https%3A//github.com/Infocatcher/Private_Tab/issues

**Real link:** https://github.com/Infocatcher/Private_Tab/issues

**Comment by Keith94** [comment]
I'm using Nightly + Tampermonkey, but the script doesn't seem to work on addons.mozilla.org domain. Can you confirm?

**Comment by Infocatcher** [comment]
Hmm, works for me after afd20ca8a6da17879960c508c4a86017b7e7cb62 commit.
