### ISSUE TITLE
[Remove fake links] некорректная работа на 4pda

### ISSUE THREAD

**Issue by Inkobob** [Infocatcher/UserScripts#14]
В последней версии, как и в предыдущих, некорректно работает на форумах 4pda.ru/forum/
Все ссылки на внешние сайты/файлы перенаправляют обратно на форум.
Для себя пока решил удалением // @include http://4pda.ru/*
Просто при очередном новом обновлении скрипта include восстанавливается...

**Comment by Infocatcher** [comment]
Подправил: 4c2d9932e904ee097935de15f1feaa551850e811
Раньше там были ссылки вида
http://4pda.ru/pages/go/?u=http%3A%2F%2Fwww.ubuntu.com%2Fdevices%2Fphone%2Foperators-and-oems
А теперь еще и хвост дописали:
http://4pda.ru/pages/go/?u=http%3A%2F%2Fwww.ubuntu.com%2Fdevices%2Fphone%2Foperators-and-oems&e=18299105&f=<ins>http%3A%2F%2F4pda.ru%2Fforum%2Findex.php%3Fshowtopic%3D415449</ins> (который и ловило...)
