### ISSUE TITLE
[Direct Images] Handle yet another image server (giphy)

### ISSUE THREAD

**Issue by Drugoy** [Infocatcher/UserScripts#15]
http://media1.giphy.com/media/yr7n0u3qzO9nG/giphy.gif > http://i.giphy.com/yr7n0u3qzO9nG.gif
http://media0.giphy.com/media/l2JHRhAtnJSDNJ2py/giphy.gif > http://i.giphy.com/l2JHRhAtnJSDNJ2py.gif
http://media4.giphy.com/media/kHJE3FKCoBpNC/giphy.gif > http://i.giphy.com/kHJE3FKCoBpNC.gif
Сервис умеет и http и https, т.к. картинка для обоих протоколов одинаковая - хотелось бы чтоб редиректилось всегда на https, потому что "а почему нет?".

**Comment by Infocatcher** [comment]
Done: 1d6221b53b896c9685e00c2c1fd034559cf5e84a

**Comment by Drugoy** [comment]
Спасибо, работает как надо :)
