### ISSUE TITLE
[Direct Images] Handle yet another image sharing service prnt.sc

### ISSUE THREAD

**Issue by Drugoy** [Infocatcher/UserScripts#16]
Там странная структура:
https://prnt.sc/aatjm2 > https://img.prntscr.com/img?url=http://i.imgur.com/3JOi9ke.png (не знаю, стоит ли в таком случае делать сразу редирект и на imgur [оттуда-то ведь картинку уже могли удалить])
https://prnt.sc/far2af > https://image.prntscr.com/image/b33d635879e14dca92384a1bb0320a30.png

**Comment by Infocatcher** [comment]
> https://prnt.sc/aatjm2 > https://img.prntscr.com/img?url=http://i.imgur.com/3JOi9ke.png (не знаю, стоит ли в таком случае делать сразу редирект и на imgur [оттуда-то ведь картинку уже могли удалить])

Главное – картинка по ссылке нормальная, открывается и в загрузки, например, не просится.
Поддержка уже была, но для <ins>http</ins>://prnt.sc/
Подправил: eec88e0080a5d5e68c686e5535277fa862630890

А еще, насколько я помню, https://addons.mozilla.org/addon/userunified-script-injector/ (единственный запускатель скриптов для мобильной версии) не умеет в `@match`. Ну да то не первый уже `@match` в коде…
