### ISSUE TITLE
[Remove fake links] mysku.ru support

### ISSUE THREAD

**Issue by g00dy22** [Infocatcher/UserScripts#17]
Namespace: `https://mysku.ru/*`

Fake link:
`https://go.mysku.ru/?r=http%3A%2F%2Fwww.aliexpress.com%2Fitem%2FSAMZHE-USB-3-0-2-0-AM%2F32949850871.html&key=ms&s=msab.ceb619b`

Real link:
`http://www.aliexpress.com/item/SAMZHE-USB-3-0-2-0-AM/32949850871.html`

Patch:
```diff
55a56
> // @include     https://mysku.ru/*
216c217,218
<
---
>       else if(/^https?:\/\/go\.mysku\.ru\/\?r=(http[^?&#\/]+)/.test(h))
>               nh = decode(RegExp.$1);
```

**Comment by Infocatcher** [comment]
Updated, thanks!
