### ISSUE TITLE
[Remove_Fake_Links] broken on twitter.com

### ISSUE THREAD

**Issue by Drugoy** [Infocatcher/UserScripts#19]
Example:
<a href="https://twitter.com/supergiantgames/status/1246087775251619840">This twit</a> contains links:
```
Bastion: http://nintendo.com/games/detail/bastion-switch/
🎤 Transistor: http://nintendo.com/games/detail/transistor-switch/
```
But upon click these links turn into t.co tracking bullshit.

In that page's DOM tree I don't see `a` node having `data-expanded-url` attribute.

**Comment by Infocatcher** [comment]
Test version: https://github.com/Infocatcher/UserScripts/blob/ab7689a5178d3575368e3a95991ae960905b69ea/Remove_Fake_Links/remove_fake_links.user.js
Only for `<a href="https://t.co/…" title="http://example.com/foo/bar">http://example.com/…</a>` to not break something.

**Comment by Drugoy** [comment]
LGTM
