### ISSUE TITLE
[Remove_Fake_Links] handle soundcloud's gate.sc

### ISSUE THREAD

**Issue by Drugoy** [Infocatcher/UserScripts#20]
Where: https://soundcloud.com/nrwrecords/daniel-deluxe-star-eater
What: "Bandcamp bit.ly/1Bdam5D" text link
Fake link: https://gate.sc/?url=http%3A%2F%2Fbit.ly%2F1Bdam5D&token=some-tracking-bullshit

**Comment by Infocatcher** [comment]
Updated: 95edcf198557d4a6aaa5135f4a805ce4ac036a75

**Comment by Drugoy** [comment]
Fix confirmed.
Awesome, thanks!
