### ISSUE TITLE
[Remove_Fake_Links] Handle 4pda.to

### ISSUE THREAD

**Issue by Drugoy** [Infocatcher/UserScripts#22]
<a href="https://4pda.to/forum/index.php?showtopic=1052056&st=2880#entry124957927">Example page with a link</a>.
```
https://4pda.to/stat/go?u=https%3A%2F%2Fozon.ru%2Ft%2FrRnK3RD&e=124957927&f=https%3A%2F%2F4pda.to%2Fforum%2Findex.php%3Fshowtopic%3D1052056%26st%3D2880%23entry124957927
```
->
```
https://ozon.ru/t/rRnK3RD
```

**Comment by Infocatcher** [comment]
4pda.ru/to works very strange for me… I've seen go*u=http redirects some time ago, but for now all links looks clear just as is, without any cleanup.

**Comment by Infocatcher** [comment]
Anyway, thanks for contributing!
