### ISSUE TITLE
Remove Fake Links: Steam linkfilter

### ISSUE THREAD

**Issue by Keith94** [Infocatcher/UserScripts#9]
On steamcommunity.com there's a linkfilter that is added to outgoing/external links. Can you please remove it.

For example the imgur link posted on here:
http://steamcommunity.com/app/329050/discussions/0/530645446308896032/

The link gets modified to this:
**https://steamcommunity.com/linkfilter/?url=**http://i.imgur.com/oNQbOqR.jpg

The bolded part should be removed obviously.

**Comment by Infocatcher** [comment]
Done: d45512dec5c5b930226291261c6e7248f10be62d
As I see `url=…` parameter isn't URL-encoded like here:
https://steamcommunity.com/linkfilter/?url=http://imgur.com/a/6T6pi#0
So, URL-specific things like `&` and `?` should be not encoded too, but it's better to find real examples.

**Comment by Keith94** [comment]
Thanks!

You can also add `http://store.steampowered.com/*` to the URL list in your script, since some links there are also affected such as the http://support.wbgames.com/ links on this page: http://store.steampowered.com/news/?appids=208650.

Links containing `?` seem to work fine, such as [this imgur one](http://steamcommunity.com/app/329050/discussions/0/530645446308896032/#c530645446314052544) (if that's what you meant).

**Comment by Infocatcher** [comment]
> You can also add `http://store.steampowered.com/*` to the URL list in your script

Done: 06194e7ab996a06eb642894ee47daa4d88a33f1c

> Links containing `?` seem to work fine

Good. Yes, I about that. With "real" URL parameters will be something like
…?url=<ins>http%3A%2F%2Fexample.com%2F%3Fa%3D0%26b%3D2%23hash</ins>&some=thing
